target_symbols:
  - BTCUSDT
  - ETHUSDT

pipeline:
  batch_size: 50 # Increased batch size for TimescaleDB efficiency

database:
  host: "localhost"
  port: 5432
  dbname: "postgres"
  user: "postgres"
  password: "1234"